simplify data returned by GET /build
joyent/conch-api pull request #1054
Opened 2020-10-28 21:12 UTC by karenetheridge

- remove options ?with_device_health, ?with_device_phases, ?with_rack_phases
- remove 'completed_user' and 'admins' properties
- replace ?include_completed option with ?started=<0|1> and ?completed=<0|1>
for filtering results (by default, all builds are returned)

2020-10-28 21:37 UTC, bdelano requested changes
as far as I know we have 3 different 'status' for builds... so we should be able to see all or any. combination... please include all 3 and allow chaining
e.g.
`started=1&created=1` or `created=1&complete=1`

2020-10-28 22:45 UTC, bdelano submitted a review, later dismissed

2020-10-29 07:07 UTC, perigrin approved these changes
I'm a little sad to lose the "Completed By" on the full list, but it saves a join.

2020-10-29 16:25 UTC, dustinryerson approved these changes

2020-10-29 16:38 UTC, merged